remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
logo: /logo.png
title: ./a2s
description: A2S Query CLI and go package
markdown: GFM
github:
  zip_url: https://github.com/WoozyMasta/a2s/zipball/master
  tar_url: https://github.com/WoozyMasta/a2s/tarball/master
  linux: https://github.com/WoozyMasta/a2s/releases/latest/download/a2s-linux-amd64
  darwin: https://github.com/WoozyMasta/a2s/releases/latest/download/a2s-darwin-arm64
  windows: https://github.com/WoozyMasta/a2s/releases/latest/download/a2s-windows-amd64.exe
